### ISSUE TITLE
bluescreen screen when using URL http://192.168.1.131:1880/ui

### ISSUE THREAD

**Issue by janvda** [hardillb/AndroidWebAutoLaunch#1]
when using URL **http://192.168.1.131:1880/ui** I get a bluescreen while that URL should give me my nodered dashboard.

It did work when entering the URL **https://www.google.com**

It is exactly the same issue as reported by Dennis in 
[http://www.hardill.me.uk/wordpress/2016/11/25/auto-launch-webpages-full-screen-on-android/#comment-143720](http://www.hardill.me.uk/wordpress/2016/11/25/auto-launch-webpages-full-screen-on-android/#comment-143720)

kr
Jan

**Comment by hardillb** [comment]
I've just pushed a new release to the Google Play store that should fix this. Please let me know if it works

**Comment by janvda** [comment]
Wow, super cool. It is working now. Thanks a lot. Jan
