### ISSUE TITLE
Support for Android 4.0.3

### ISSUE THREAD

**Issue by vosmani** [hardillb/AndroidWebAutoLaunch#10]
A great app and very useful!

I was wondering how difficult it would be to support Android 4.0.3? 

I have a bunch of older devices that I use as dashboards, all running Android ICS.

Thanks!

**Comment by hardillb** [comment]
I'm sorry, but I have no interest in working out what it would take to get it to work on something that old.

All the source is here, so feel free to see if you get it to build with that as a target and I'll look at any pull request that doesn't break anything.
