### ISSUE TITLE
Smart TV support

### ISSUE THREAD

**Issue by akryeem** [hardillb/AndroidWebAutoLaunch#11]
Hi,
Do you have a plan to support smart tv?

**Comment by hardillb** [comment]
None at all

You'd have to provide context to how it would be used on a smart tv.

**Comment by akryeem** [comment]
I think the usecase is trivial:
I have #X SmartTVs where I want to show some static website on TVs' startup...
Anyway, do you mind if I make the modifications and publish a new app based on your code? (including the about_html of course)

**Comment by hardillb** [comment]
Feel free to have a go, if it can be done as pull request so that both phone/tablet and TV versions can live in the same repo then all the better then there is only one place that needs updating in the furture
