### ISSUE TITLE
Conflicts with gesture navigation mode

### ISSUE THREAD

**Issue by leoric** [hardillb/AndroidWebAutoLaunch#12]
Conflicts with gesture navigation mode where swipe from a side is used to go back instead of the "Back' button

**Comment by hardillb** [comment]
Probably,

The whole thing was written long before Google decided to introduce that interaction pattern.

Feel free to suggest an alternative.

**Comment by leoric** [comment]
long tap

**Comment by hardillb** [comment]
I will await your Pull-Request then

**Comment by leoric** [comment]
I don't know java, here is a stub in Kotlin that listens for long tap and toggles visibility of object
```
webView.setOnLongClickListener {
            if (View.GONE === address.visibility) {
                address.visibility = View.VISIBLE
            } else {
                address.visibility = View.GONE
            }
            true
        }
```
